version: "3.8"
services:
  api:
    build: .
    platform: linux/amd64
    environment:
      - REDIS_URL=redis://cache:6379/
    ports:
      - 8080:8080
    depends_on:
      - pg-db
  pg-db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=academy
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  cache:
    image: redis:7.2.3
    expose:
      - 6379
volumes:
  # The `db-data` volume persists the database data between container restarts.
  db-data:
