version: "3.8"
services:
  api:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:academy@pg-db:5432/learnhub-db?schema=public
      - PORT=8080
      - JWT_SECRET=0x7393fbc185a7fb62ef8a451d3e526bf30575d721
    ports:
      - 8080:8080
    depends_on:
      - pg-db
  pg-db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=academy
    volumes:
      - learnhub-db-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  learnhub-db-vol:
    name: e53333ec7a4ecaaab93aeed95f96b2457848f3a66ba1dfdfc5b2f7de194fa277
