name: Docker build image

on: push

jobs:
  hello-word:
    runs-on: ubuntu-latest
    steps:
      - name: Print out hello-word
        run: echo "Hello, world."
      - name: Check out
        uses: actions/checkout@v3
      - name: Print out lists
        run: ls
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          echo "SHORTENED_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT &&
          echo "REF_TAG=$(sed -e "s/\//\./g" <<< $REF_NAME)" >> $GITHUB_OUTPUT
        id: params
        env:
          GITHUB_SHA: ${{ github.sha }}
          REF_NAME: ${{ github.ref_name }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/learnhub-api-project:${{ steps.params.outputs.REF_TAG }}-${{ steps.params.outputs.SHORTENED_SHA }}
