name: Docker build image

on: push

jobs:
  hello-word:
    runs-on: ubuntu-latest
    steps:
      - name: Print out hello-word
        run: echo "Hello, world."
      - name: Check out
        uses: actions/checkout@v3
        with:
          username: ${{ secrets.DOKERHUB_USERNAME}}
          prassword: ${{ secrets.DOKERHUB_TOKEN}}
      - name: Print out lists
        run: ls
